urls.py
from django.urls import path
from . import views
from django.contrib.auth import login

app_name = 'users'
urlpatterns = [
    path('register/', views.registration, name='register'),
    path('register/tutor', views.tutor_registration, name='tutorregister'),
]

models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    # age = forms.IntegerField()
    # sex = forms.ChoiceField(choices=(('male', 'Male'), ('female','Female ')))
    # description = forms.CharField(widget=forms.Textarea)
    # rate = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class':"form-control", 'aria-describedby':"emailHelp", 'placeholder':"Enter email"})
        self.fields['username'].widget.attrs.update({'placeholder': 'Username', 'class':'form-control',})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Password', 'class':'form-control',})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password', 'class':'form-control',})
    #     self.fields['age'].widget.attrs.update({'class':'form-control',})
    #     self.fields['sex'].widget.attrs.update({'class':"form-control"})
    #     self.fields['rate'].widget.attrs.update({'class':'form-control',})       
    #     self.fields['description'].widget.attrs.update({'class':"form-control"})
        

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 
        # 'age', 'sex',
        # 'rate', 'description'
        ]

# class RegisterProfile()

qual = [ 
('psle', 'PSLE'),
('olvl', 'O Levels'),
('alvl', 'A Levels'),
('IB', 'IB'),
('diploma', 'Diploma'),
('degree', "Bachlor's Degree"),
('honors', 'Honors'),
('masters', "Masters"),
('phd', 'PHD'),
('others','Others')
]

class TutorRegisterForm(UserCreationForm):
    email = forms.EmailField()
    age = forms.IntegerField()
    sex = forms.ChoiceField(choices=(('male', 'Male'), ('female','Female')))
    qualifications = forms.MultipleChoiceField(choices=qual,widget=forms.CheckboxSelectMultiple,)
    description = forms.CharField(widget=forms.Textarea)
    rate = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class':"form-control", 'aria-describedby':"emailHelp", 'placeholder':"Enter email"})
        self.fields['username'].widget.attrs.update({'placeholder': 'Username', 'class':'form-control',})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Password', 'class':'form-control',})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Confirm Password', 'class':'form-control',})
        self.fields['age'].widget.attrs.update({'class':'form-control',})
        self.fields['sex'].widget.attrs.update({'class':"form-control"})
        self.fields['rate'].widget.attrs.update({'class':'form-control',})       
        self.fields['description'].widget.attrs.update({'class':"form-control"})

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'age', 'sex',
        'rate', 'qualifications', 'description']

views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm, TutorRegisterForm
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import login_required

# Create your views here.

def registration(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account was successfully created for ' + username)
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

def my_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('first_app/home')


def logout_view(request):
    logout(request)
    return redirect('first_app/home')

def login_error(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login_error.html')

def tutor_registration(request):
    if request.method == 'POST':
        form = TutorRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + username)
            return redirect('login')
    else:
        form = TutorRegisterForm()
    return render(request, 'users/tutorregister.html', {'form':form})
    

templates/users/register.html
{% extends 'first_app/base.html' %}
<!DOCTYPE html>
{% block content %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>register</title>
  </head>
  <body>
    <p1 class="lead">Sign up page</p1>
    <br>
    <hr>
    <form class="register" action="{% url 'users:register' %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
    <br>
    {{form.errors}}
    <p>Already have an account?<a href="/login"> Login</a></p>
    <script type="text/javascript">
      var help_text = document.getElementsByClassName('helptext')


    </script>
  </body>
</html>
{% endblock content %}

templates/users/tutorregister.html
{% extends 'first_app/base.html' %}
<!DOCTYPE html>
{% block content %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>register</title>
  </head>
  <body>
    <p1 class="lead">Tutor sign up page</p1>
    <br>
    <hr>
    {{form.errors}}
    <form class="register" action="{% url 'users:tutorregister' %}" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
    <br>
    <p>Already have an account?<a href="/login"> Login</a></p>
    <script type="text/javascript">
      var help_text = document.getElementsByClassName('helptext')


    </script>
  </body>
</html>
{% endblock content %}